In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [0]:
x = torch.empty(5, 3)
print(x)

tensor([[1.2291e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix:



In [0]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8131, 0.9760, 0.0250],
        [0.2526, 0.7598, 0.0531],
        [0.9447, 0.9461, 0.7815],
        [0.8422, 0.2225, 0.9818],
        [0.2587, 0.7995, 0.2109]])


Construct a matrix filled zeros and of dtype long:



In [0]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [0]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [0]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0198,  0.4131,  0.8526],
        [-2.2900,  0.4638, -0.2867],
        [ 0.4932, -0.7783, -0.7664],
        [ 0.2218, -0.1264,  0.6541],
        [ 0.7788,  0.1582,  2.1617]])


Get its size:



In [0]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [0]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.8880,  0.4535,  1.3966],
        [-1.4154,  1.0664,  0.6642],
        [ 1.1451, -0.1896, -0.6289],
        [ 1.1850,  0.7426,  1.6142],
        [ 1.7589,  0.8261,  2.6879]])


Addition: syntax 2



In [0]:
print(torch.add(x, y))

tensor([[ 0.8880,  0.4535,  1.3966],
        [-1.4154,  1.0664,  0.6642],
        [ 1.1451, -0.1896, -0.6289],
        [ 1.1850,  0.7426,  1.6142],
        [ 1.7589,  0.8261,  2.6879]])


Addition: providing an output tensor as argument



In [0]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.8880,  0.4535,  1.3966],
        [-1.4154,  1.0664,  0.6642],
        [ 1.1451, -0.1896, -0.6289],
        [ 1.1850,  0.7426,  1.6142],
        [ 1.7589,  0.8261,  2.6879]])


Addition: in-place



In [0]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.8880,  0.4535,  1.3966],
        [-1.4154,  1.0664,  0.6642],
        [ 1.1451, -0.1896, -0.6289],
        [ 1.1850,  0.7426,  1.6142],
        [ 1.7589,  0.8261,  2.6879]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [0]:
print(x[:, 1])

tensor([ 0.4131,  0.4638, -0.7783, -0.1264,  0.1582])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [0]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [0]:
x = torch.randn(2, 4, 3)
#x.transpose(0,1).shape
x.size()
x.transpose(0,2).shape

torch.Size([3, 4, 2])

transpose only applies to 2 axis, while permute can be applied to all the axes at the same time.
For example

In [0]:


a = torch.rand(1,2,3,4)
print(a.transpose(0,3).transpose(1,2).size())
print(a.permute(3,2,1,0).size())# same as np.transpose
print(a.permute(2,3,1,0).size())# This not the same as reshape

torch.Size([4, 3, 2, 1])
torch.Size([4, 3, 2, 1])
torch.Size([3, 4, 2, 1])


In [0]:
a.transpose(0,3)
a.shape# See how a is not changed

torch.Size([1, 2, 3, 4])

when you call transpose(), PyTorch doesn't generate new tensor with new layout, it just modifies meta information in Tensor object so offset and stride are for new shape. The transposed tensor and original tensor are indeed sharing the memory!

Here bytes are still allocated in one block of memory but the order of the elements is different!

When you call contiguous(), it actually makes a copy of tensor so the order of elements would be same as if tensor of same shape created from scratch.

Normally you don't need to worry about this. If PyTorch expects contiguous tensor but if its not then you will get RuntimeError: input is not contiguous and then you just add a call to contiguous().

In [0]:
print(a.transpose(0,3).contiguous().shape)

a.shape

torch.Size([4, 2, 3, 1])


torch.Size([1, 2, 3, 4])

If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [0]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-2.0151])
-2.015139579772949


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [0]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [0]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [0]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [0]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Convert to numpy array

In [0]:
import numpy as np
x = torch.randn(4, 4)
x1 = np.array(x)
x1 += 1
print(x)
print(x1)# See how the two tensors are not linked

tensor([[ 1.5206,  1.9469, -1.7359,  1.6695],
        [ 1.6953, -0.9151,  1.2206,  0.0844],
        [-0.4851,  0.4263,  1.9474, -0.9403],
        [-0.7241,  0.1669, -0.8165,  0.4246]])
[[ 2.5206027   2.946856   -0.73586607  2.6695101 ]
 [ 2.695272    0.08494896  2.2206295   1.0843753 ]
 [ 0.51487714  1.4262674   2.9473774   0.05973274]
 [ 0.2759241   1.1669002   0.1835112   1.4246122 ]]


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[ 2.5206,  2.9469, -0.7359,  2.6695],
        [ 2.6953,  0.0849,  2.2206,  1.0844],
        [ 0.5149,  1.4263,  2.9474,  0.0597],
        [ 0.2759,  1.1669,  0.1835,  1.4246]], device='cuda:0')
tensor([[ 2.5206,  2.9469, -0.7359,  2.6695],
        [ 2.6953,  0.0849,  2.2206,  1.0844],
        [ 0.5149,  1.4263,  2.9474,  0.0597],
        [ 0.2759,  1.1669,  0.1835,  1.4246]], dtype=torch.float64)


In [0]:
x.cuda()

tensor([[ 1.5206,  1.9469, -1.7359,  1.6695],
        [ 1.6953, -0.9151,  1.2206,  0.0844],
        [-0.4851,  0.4263,  1.9474, -0.9403],
        [-0.7241,  0.1669, -0.8165,  0.4246]], device='cuda:0')